import { ChunkExtractor } from '@loadable/server';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { StaticRouter } from "react-router-dom";
import App from '../App';
/**
 * @param location {string}
 * @returns {string} - html
 */
export function render(location){

    // This is the stats file generated by webpack loadable plugin
    const statsFile = require('../../public/loadable-stats.json')
    // We create an extractor from the statsFile
    const extractor = new ChunkExtractor({ statsFile });
    
    const html = ReactDOMServer.renderToString(
      extractor.collectChunks(
        <StaticRouter location={location} context={{}}>
          <App/>
        </StaticRouter>
      )
    );
  
    return html
}

